project/open_ricostruzione/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
# from django.contrib import admin
from django.views.generic import ListView
from .models import Comune, Soggetto, SoggettoAttuatore
from .views import HomeView, StaticView, RicostruzionePubblicaInterventoListView, RicostruzionePrivataInterventoListView, \
    AttivitaProduttivaInterventoListView, AltroInterventoListView, ComuneDetailView, SoggettoDetailView, InterventoDetailView, \
    MySearchView, DonazioneListView

# admin.autodiscover()


urls = [
    url(r'^$', HomeView.as_view(template_name='pages/home.html'), name='home'),

    url(r'^ricostruzione-pubblica$', RicostruzionePubblicaInterventoListView.as_view(template_name='pages/interventoricostruzionepubblica_list.html'), name='ricostruzione-pubblica'),
    url(r'^ricostruzione-privata$', RicostruzionePrivataInterventoListView.as_view(template_name='pages/interventoricostruzioneprivata_list.html'), name='ricostruzione-privata'),
    url(r'^ricostruzione-attivitaproduttive$', AttivitaProduttivaInterventoListView.as_view(template_name='pages/interventoattivitaproduttive_list.html'), name='ricostruzione-attivitaproduttive'),
    url(r'^ricostruzione-altro$', AltroInterventoListView.as_view(template_name='pages/interventoaltro_list.html'), name='ricostruzione-altro'),

    url(r'^ricostruzione-dove$', ListView.as_view(template_name='pages/comune_list.html', model=Comune), name='comune-list'),

    url(r'^donazioni$', DonazioneListView.as_view(template_name='pages/donazione_list.html'), name='donazione-list'),

    url(r'^comune/(?P<slug>[-\w]+)$', ComuneDetailView.as_view(template_name='pages/comune_detail.html'), name='comune-detail'),
    url(r'^intervento/(?P<slug>[-\w]+)$', InterventoDetailView.as_view(), name='intervento-detail'),
    url(r'^soggetto/(?P<pk>\d+)$', SoggettoDetailView.as_view(template_name='pages/soggetto_detail.html', model=Soggetto), name='soggetto-detail'),
    url(r'^soggettoattuatore/(?P<slug>[-\w]+)$', SoggettoDetailView.as_view(template_name='pages/soggetto_detail.html', model=SoggettoAttuatore), name='soggettoattuatore-detail'),

    url(r'^(?P<page_slug>chi-siamo|faq|contatti|privacy|licenze|open-data)$', StaticView.as_view(), name='static'),

    url(r'^cerca/', MySearchView.as_view(), name='search'),

    # url(r'^admin/', admin.site.urls),
]
urlpatterns = urls

# static and media urls not works with DEBUG = True, see static function.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns.append(
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

project/open_ricostruzione/models/altriinterventi.py
# -*- coding: utf-8 -*-
from django.db import models
from .general import InterventoBase


class InterventoAltro(InterventoBase):
    IDPREFIX = 'A'

    CATEGORIA_OGGETTO = (
        ('C', 'Chiese'),
        ('P', 'Edifici pubblici'),
        ('S', 'Impianti sportivi e ricreativi'),
        ('T', 'Moduli abitativi temporanei'),
        ('U', 'Scuole e Università'),
    )

    AGGREGATION_FILTER = {
        'field': 'categoria_oggetto',
        'options': list(CATEGORIA_OGGETTO)
    }

    id = models.PositiveIntegerField(primary_key=True, db_index=True)
    categoria_oggetto = models.CharField(max_length=1, choices=CATEGORIA_OGGETTO)
    atto_concessione = models.CharField(max_length=20, null=True, blank=True)
    data_concessione = models.DateField(null=True, blank=True)
    data_inizio_lavori = models.DateField(null=True, blank=True)
    data_fine_lavori_prevista = models.DateField(null=True, blank=True)
    data_fine_lavori_reale = models.DateField(null=True, blank=True)
    data_intervento = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name = 'Altri interventi'
        verbose_name_plural = 'Altri interventi'

project/open_ricostruzione/models/attivitaproduttive.py
# -*- coding: utf-8 -*-
from django.db import models
from .general import InterventoBase


class InterventoAttivitaProduttiva(InterventoBase):
    IDPREFIX = 'S'

    TIPOLOGIA_INTERVENTO = (
        ('RD', "Ricostruzione ed eventuale demolizione dell'immobile"),
        ('RD-SM', "Ricostruzione ed eventuale demolizione dell'immobile Solo miglioramento sismico"),
        ('RD-SR', "Ricostruzione ed eventuale demolizione dell'immobile Solo ripristino"),
        ('RM', 'Ripristino e miglioramento sismico'),
        ('RM-RD', "Ripristino e miglioramento sismico Ricostruzione ed eventuale demolizione dell'immobile"),
        ('RM-RD-SM', "Ripristino e miglioramento sismico Ricostruzione ed eventuale demolizione dell'immobile Solo miglioramento sismico"),
        ('RM-RD-SR', "Ripristino e miglioramento sismico Ricostruzione ed eventuale demolizione dell'immobile Solo ripristino"),
        ('RM-RD-SR-SM', "Ripristino e miglioramento sismico Ricostruzione ed eventuale demolizione dell'immobile Solo ripristino Solo miglioramento sismico"),
        ('RM-SM', 'Ripristino e miglioramento sismico Solo miglioramento sismico'),
        ('RM-SR', 'Ripristino e miglioramento sismico Solo ripristino'),
        ('SR', 'Solo ripristino'),
    )

    SETTORE_ECONOMICO = (
        ('A', 'agricoltura'),
        # ('M', 'agrimodena'),
        ('C', 'commercio'),
        ('I', 'industria'),
    )

    AGGREGATION_FILTER = {
        'field': 'settore_economico',
        'options': [(x[0], x[1].capitalize()) for x in SETTORE_ECONOMICO]
    }

    id = models.PositiveIntegerField(primary_key=True, db_index=True)
    numero_protocollo = models.CharField(max_length=13, unique=True, db_index=True)
    tipologia_intervento = models.CharField(max_length=11, choices=TIPOLOGIA_INTERVENTO, null=True, blank=True)
    settore_economico = models.CharField(max_length=1, choices=SETTORE_ECONOMICO)
    interventi_presentati = models.CharField(max_length=80)  # ['Beni strumentali', 'Delocalizzazione definitiva', 'Delocalizzazione temporanea', 'Immobili', 'Prodotti DOP/IGP', 'Scorte']
    data_decreto_concessione = models.DateField(null=True, blank=True)
    beneficiario = models.CharField(max_length=256, null=True, blank=True)
    data_protocollo_domanda = models.DateField()
    contributo_concesso_immobili = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    contributo_concesso_beni_strumentali = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    contributo_concesso_scorte = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    contributo_concesso_delocalizzazione_temporanea = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    contributo_concesso_prodotti = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)

    @property
    def interventi_presentati_display(self):
        return ', '.join(self.interventi_presentati.strip('|').split('|'))

    class Meta:
        verbose_name = 'Intervento di ricostruzione attività produttive'
        verbose_name_plural = 'Interventi di ricostruzione attività produttive'

project/open_ricostruzione/models/general.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.utils.functional import cached_property
from django_extensions.db.fields import AutoSlugField
from .managers import InterventoQuerySet, DonazioneQuerySet


class Comune(models.Model):
    id = models.PositiveIntegerField(primary_key=True, db_index=True)
    denominazione = models.CharField(max_length=30)
    codice_istat = models.CharField(max_length=6)
    provincia_denominazione = models.CharField(max_length=15)
    provincia_sigla = models.CharField(max_length=2)
    regione_denominazione = models.CharField(max_length=15)
    regione_codice = models.CharField(max_length=2)
    slug = AutoSlugField(populate_from='denominazione', max_length=30)

    @property
    def denominazione_con_provincia(self):
        return '{} ({})'.format(self.denominazione, self.provincia_sigla)

    @property
    def codice(self):
        return '{}{}'.format(int(self.regione_codice), self.codice_istat)

    @property
    def provincia_codice(self):
        return self.codice_istat[3:]

    def get_absolute_url(self):
        return reverse('comune-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.denominazione_con_provincia

    class Meta:
        ordering = ('regione_denominazione', 'provincia_denominazione', 'denominazione')
        verbose_name = 'Comune'
        verbose_name_plural = 'Comuni'


class Soggetto(models.Model):
    id = models.PositiveIntegerField(primary_key=True, db_index=True)
    impresa_codice_fiscale = models.CharField(max_length=16, null=True, blank=True)
    impresa_partita_iva = models.CharField(max_length=11, null=True, blank=True)
    impresa_ragione_sociale = models.CharField(max_length=256, null=True, blank=True)
    anno_denuncia_addetti = models.CharField(max_length=4, null=True, blank=True)
    numero_addetti_familiari = models.PositiveSmallIntegerField(null=True, blank=True)
    numero_addetti_subordinati = models.PositiveSmallIntegerField(null=True, blank=True)
    sede_indirizzo = models.CharField(max_length=256, null=True, blank=True)
    sede_numero_civico = models.CharField(max_length=10, null=True, blank=True)
    sede_cap = models.CharField(max_length=5, null=True, blank=True)
    sede_comune = models.CharField(max_length=50, null=True, blank=True)
    sede_provincia = models.CharField(max_length=2, null=True, blank=True)

    @cached_property
    def interventi(self):
        from django.db.models import Q
        return Intervento.objects.filter(Q(esecutore=self) | Q(progettista=self))

    def get_absolute_url(self):
        return reverse('soggetto-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.impresa_ragione_sociale

    class Meta:
        verbose_name = 'Impresa / Progettista'
        verbose_name_plural = 'Imprese / Progettisti'


class SoggettoAttuatore(models.Model):
    denominazione = models.CharField(max_length=128, unique=True)
    slug = AutoSlugField(populate_from='denominazione', max_length=128)

    def get_absolute_url(self):
        return reverse('soggettoattuatore-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.denominazione

    class Meta:
        verbose_name = 'Soggetto attuatore'
        verbose_name_plural = 'Soggetti attuatori'


class Intervento(models.Model):
    STATO_PRATICA = (
        ('1', 'Decreti Concessione'),
        ('2', 'Richiesta In Istruttoria'),
        ('3', 'Richiesta Futura'),
        # ('4', 'Richiesta Non Approvata'),
        ('4', 'A Programma'),
    )

    STATO_CANTIERE = (
        ('1', 'Cantiere In Corso'),
        ('2', 'Cantiere Completato'),
        ('3', 'Da Avviare (Contributo Assegnato)'),
    )

    cup = models.CharField(max_length=20, null=True, blank=True)
    descrizione_intervento = models.CharField(max_length=1024, null=True, blank=True)

    importo_assegnato = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    importo_pagato = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)

    stato_pratica = models.CharField(max_length=1, choices=STATO_PRATICA)
    stato_cantiere = models.CharField(max_length=1, choices=STATO_CANTIERE, null=True, blank=True)

    indirizzo = models.CharField(max_length=256, null=True, blank=True)
    numero_civico = models.CharField(max_length=20, null=True, blank=True)

    comune = models.ForeignKey(Comune, related_name='interventi', null=True, blank=True)

    latitudine = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitudine = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)

    giorni_istruttoria = models.PositiveSmallIntegerField(null=True, blank=True)
    giorni_cantiere = models.SmallIntegerField(null=True, blank=True)

    esecutore = models.ForeignKey(Soggetto, related_name='interventi_esecutore', null=True, blank=True)
    progettista = models.ForeignKey(Soggetto, related_name='interventi_progettista', null=True, blank=True)

    soggetto_attuatore = models.ForeignKey(SoggettoAttuatore, related_name='interventi', null=True, blank=True)

    slug = AutoSlugField(populate_from='intervento_unique_id', max_length=30)

    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    objects = InterventoQuerySet.as_manager()

    @property
    def intervento_unique_id(self):
        return self.content_object.unique_id

    @property
    def indirizzo_completo(self):
        if self.numero_civico:
            return '{}, {}'.format(self.indirizzo, self.numero_civico)
        else:
            return '{}'.format(self.indirizzo)

    def get_absolute_url(self):
        return reverse('intervento-detail', kwargs={'slug': self.slug})

    def __str__(self):
        if self.content_type.model == 'interventoricostruzioneprivata':
            return '{}{}'.format('{} - '.format(self.indirizzo_completo) if self.indirizzo else '', self.content_object.descrizione)
        elif self.content_type.model == 'interventoattivitaproduttiva':
            return self.content_object.beneficiario or 'beneficiario non presente'
        else:
            return self.descrizione_intervento

    class Meta:
        unique_together = ('content_type', 'object_id')
        verbose_name = 'Intervento'
        verbose_name_plural = 'Interventi'


class Pratica(models.Model):
    intervento = models.ForeignKey(Intervento, related_name='pratiche')
    data = models.DateField(null=True, blank=True)
    tipo = models.CharField(max_length=25)
    importo = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)

    class Meta:
        ordering = ('intervento', 'data', 'id')
        verbose_name = 'Pratica'
        verbose_name_plural = 'Pratiche'


class Donazione(models.Model):
    TIPOLOGIA_CEDENTE = (
        ('0', 'Altro'),
        ('1', 'Associazioni'),
        ('2', 'Enti pubblici'),
        ('3', 'Comuni'),
        ('4', 'Cittadini'),
        ('5', 'Aziende'),
        ('6', 'Regioni'),
        ('7', 'Province'),
        ('8', 'SMS solidale'),
    )

    TIPOLOGIA_DONAZIONE = (
        ('1', 'Diretta'),
        ('2', 'Regione'),
    )

    DESTINAZIONE = (
        ('0', 'Ricostruzione pubblica'),
        ('1', 'Acquisto arredi e attrezzature per edifici scolastici'),
        ('2', 'Interventi di incremento resistenza antisismica edifici pubblici'),
        ('3', 'Contributi alle famiglie'),
        ('4', 'Contributi alle associazioni di volontariato'),
        ('5', 'Interventi di manutenzione ordinaria del patrimonio pubblico danneggiato'),
        ('6', 'Attrezzature sportive'),
        ('7', 'Altro'),
        ('8', 'Da destinare'),
    )

    denominazione = models.CharField(max_length=256)
    tipologia_cedente = models.CharField(max_length=2, choices=TIPOLOGIA_CEDENTE)
    tipologia_donazione = models.CharField(max_length=2, choices=TIPOLOGIA_DONAZIONE)
    data = models.DateField()
    importo = models.DecimalField(max_digits=12, decimal_places=2)
    comune = models.ForeignKey(Comune, related_name='donazioni')
    intervento = models.ForeignKey(Intervento, related_name='donazioni', null=True, blank=True)
    destinazione = models.CharField(max_length=1, choices=DESTINAZIONE, null=True, blank=True)

    objects = DonazioneQuerySet.as_manager()

    def __str__(self):
        # return 'ANONIMO' if self.get_tipologia_cedente_display() == 'Cittadini' or not self.denominazione else self.denominazione
        return self.denominazione or 'ANONIMO'

    class Meta:
        ordering = ('-importo', 'data')


class InterventoBase(models.Model):
    IDPREFIX = ''

    interventi = GenericRelation(Intervento, related_query_name='%(class)s')

    @classmethod
    def get_lookup(cls, field):
        return '{}__{}'.format(cls.__name__.lower(), field)

    @property
    def unique_id(self):
        return '{}{}'.format(self.IDPREFIX, self.id)

    class Meta:
        abstract = True

project/open_ricostruzione/forms.py
# -*- coding: utf-8 -*-
from django import forms
from haystack.forms import FacetedSearchForm


class MySearchForm(FacetedSearchForm):
    type = forms.CharField(required=False)
    subtype = forms.CharField(required=False)
    comune = forms.CharField(required=False)
    soggetto_attuatore = forms.CharField(required=False)
    soggetto = forms.CharField(required=False)

    def no_query_found(self):
        return self.searchqueryset.all()

    def search(self):
        sqs = super(MySearchForm, self).search()

        for fld in ('type', 'subtype', 'comune', 'soggetto', 'soggetto_attuatore'):
            if self.cleaned_data[fld]:
                sqs = sqs.filter(**{fld: self.cleaned_data[fld]})

        sqs = sqs.order_by('name_s')

        sqs = sqs.load_all()

        return sqs

project/open_ricostruzione/templates/pages/comune_list.html
{% extends 'base.html' %}

{% block page_title %}Dove si interviene{% endblock %}

{% block content %}
    <section class="box-white">
        <div class="container">
            <h2 class="red mt-0">Dove si interviene</h2>

            {% regroup object_list by provincia_denominazione as comuni_by_province %}

            <div class="row">
                {% for comuni_by_provincia in comuni_by_province %}
                    <div class="col-md-3">
                        <h3>{{ comuni_by_provincia.grouper }}</h3>
                        <nav>
                            <ul class="nav-list">
                                {% for comune in comuni_by_provincia.list %}
                                    <li><a href="{{ comune.get_absolute_url }}">{{ comune.denominazione }}</a></li>
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

project/open_ricostruzione/templates/pages/intervento_detail.html
{% extends 'base.html' %}

{% load staticfiles humanize sekizai_tags jsonify verbose_name %}

{% block page_title %}{{ object.content_object|model_verbose_name }}{% endblock %}

{% block content %}
    <main class="box-white">
        <div class="container">
            <div class="row">
                <div class="col-md-{{ donazioni.totale_donazioni|yesno:'8,12' }}">
                    <h2 class="mt-0 lh-1_5">
                        {% block descrizione_intervento %}<span class="red">{{ object }}</span>{% if object.comune %}<br/>{{ object.comune }}{% endif %}{% endblock %}
                    </h2>
                    <p class="grey mb-0">{{ object.content_object|model_verbose_name|upper }}</p>
                </div>
                {% if donazioni.totale_donazioni %}
                    <div class="col-md-4">
                        <div class="pl-2 bl-1">
                            <h3><span class="blue-light">Donazioni</span></h3>
                            <p class="lead">Questo intervento ha ricevuto<br/><span class="huge">{{ donazioni.totale_donazioni|intcomma }}</span> donazion{{ donazioni.totale_donazioni|pluralize:'e,i' }} per un totale di<br/><span class="big blue-light">€ {{ donazioni.totale_importo|intcomma }}</span></p>
                            <a href="{% url 'donazione-list' %}?intervento={{ object.slug }}" class="btn btn-danger py-0" style="background-color: #005F86; border-color: #5895D9">VEDI TUTTE</a>
                        </div>
                    </div>
                {% endif %}
            </div>

            <h3 class="my-2">
                <span class="mr-2">Pratica: <i class="circle circle-{% if object.stato_pratica == '1' %}green{% elif object.stato_pratica == '2' %}yellow{% elif object.stato_pratica == '3' %}red{% endif %}"></i>  {{ object.get_stato_pratica_display|default_if_none:'' }}</span>
                <span class="grey">|</span>
                <span class="ml-2">Cantiere: <i class="circle circle-{% if object.stato_cantiere == '2' %}green{% elif object.stato_cantiere == '1' %}yellow{% elif object.stato_cantiere == '3' %}red{% endif %}"></i> {{ object.get_stato_cantiere_display|default_if_none:'' }}</span>
            </h3>

            <section class="row mb-4">
                <div class="col-md-{{ object.content_object.importo_cofinanziamento|yesno:'4,6' }}">
                    <div class="bg-red py-1 text-center">
                        <p class="lead">Importo assegnato</p>
                        <h2>€ {{ object.importo_assegnato|default_if_none:0|intcomma }}</h2>
                    </div>
                </div>
                <div class="col-md-{{ object.content_object.importo_cofinanziamento|yesno:'4,6' }}">
                    {% with pratiche=object.pratiche.all %}
                        <div class="bg-red py-1 text-center{% if pratiche|length %} red-arrow-b{% endif %}">
                            <p class="lead">Importo pagato</p>
                            <h2>€ {{ object.importo_pagato|default_if_none:0|intcomma }}</h2>
                        </div>
                        {% if pratiche|length %}
                            <div class="mt-1">
                                {% for pratica in pratiche %}
                                    <p>
                                        <span class="pull-right"><strong>€ {{ pratica.importo|intcomma }}</strong></span>
                                        <strong>{{ pratica.tipo }}</strong>{% if pratica.data %}<br/>({{ pratica.data }}){% endif %}
                                    </p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    {% endwith %}
                </div>
                {% if object.content_object.importo_cofinanziamento %}
                    <div class="col-md-4">
                        <div class="bg-red py-1 text-center red-arrow-b">
                            <p class="lead">Cofinanziamenti</p>
                            <h2>€ {{ object.content_object.importo_cofinanziamento|intcomma }}</h2>
                        </div>
                        <div class="mt-1">
                            {% for importo_cofinanziamento in object.content_object.importi_cofinanziamenti %}
                                <p>
                                    <span class="pull-right"><strong>€ {{ importo_cofinanziamento.importo|intcomma }}</strong></span>
                                    <strong>{{ importo_cofinanziamento.nome }}</strong>
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </section>

            {% block details %}{% endblock %}

            <section class="row mb-2">
                <div class="col-md-12">
                    {% if object.indirizzo %}
                        <p class="lead"><strong>Indirizzo:</strong> {{ object.indirizzo_completo }}{% if object.comune %} - {{ object.comune }}{% endif %}</p>
                    {% endif %}

                    {% if map_info.poi_list|length %}
                        <div id="COMUNI" class="map" data-type="totale"></div>

                        {% addtoblock 'js' strip %}
                        <script src="{% static 'leaflet/leaflet.js' %}"></script>
                        <script src="{% static 'js/config_map.js' %}"></script>
                        <script src="{% static 'js/class-OricMap.js' %}"></script>
                        <script>
                            $(document).ready(function () {
                                OricMap.init(config_map);
                            });
                        </script>
                        {% endaddtoblock %}

                        {% addtoblock 'js' strip %}
                        <script>
                            var map_info = {{ map_info|jsonify }};
                        </script>
                        {% endaddtoblock %}

                        {% addtoblock 'css' strip %}
                            <link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}">
                        {% endaddtoblock %}
                    {% endif %}
                </div>
            </section>
        </div>
    </main>
{% endblock %}

project/open_ricostruzione/templates/pages/interventoaltro_list.html
{% extends 'pages/intervento_list.html' %}

{% block page_title %}Altri interventi{% endblock %}

{% block incipit %}
    <h2 class="mt-0"><span class="red">Altri</span> interventi</h2>
    <p class="lead mb-1">{% include 'includes/interventoaltro_text.html' %}</p>
{% endblock %}

{% block more_content %}
    {% include 'includes/interventoaltro_charts.html' with data=data only %}
{% endblock %}

project/open_ricostruzione/templates/pages/interventoattivitaproduttiva_detail.html
{% extends 'pages/intervento_detail.html' %}

{% block details %}
    <section class="row mb-4">
        <div class="col-lg-6">
            <p class="lead bb-1 mb-0 lh-1_8">Tipologia intervento: <strong>{{ object.content_object.get_tipologia_intervento_display|default_if_none:'' }}</strong></p>
            <p class="lead bb-1 mb-0 lh-1_8">Settore economico: <strong>{{ object.content_object.get_settore_economico_display|default_if_none:'' }}</strong></p>
            <p class="lead bb-1 mb-0 lh-1_8">Numero CUP e data di concessione: <strong>{{ object.content_object.data_decreto_concessione|default_if_none:'' }} - {{ object.cup|default_if_none:'' }}</strong></p>
        </div>
        <div class="col-lg-6">
            <p class="lead bb-1 mb-0 lh-1_8">Progettista: <strong>{% if object.progettista %}<a href="{{ object.progettista.get_absolute_url }}">{{ object.progettista }}</a>{% endif %}</strong></p>
            <p class="lead bb-1 mb-0 lh-1_8">Esecutore: <strong>{% if object.esecutore %}<a href="{{ object.esecutore.get_absolute_url }}">{{ object.esecutore }}</a>{% endif %}</strong></p>
            <p class="lead bb-1 mb-0 lh-1_8">Interventi presentati: <strong>{{ object.content_object.interventi_presentati_display }}</strong></p>
        </div>
    </section>
{% endblock %}

project/open_ricostruzione/templates/pages/interventoattivitaproduttive_list.html
{% extends 'pages/intervento_list.html' %}

{% block page_title %}Ricostruzione delle attività produttive{% endblock %}

{% block incipit %}
    <h2 class="mt-0"><span class="red">Ricostruzione</span> delle attività produttive</h2>
    <p class="lead mb-1">{% include 'includes/interventoattivitaproduttive_text.html' %}</p>
{% endblock %}

{% block select_label %}Visualizza il settore economico{% endblock %}

{% block more_content %}
    {% include 'includes/interventoattivitaproduttive_charts.html' with data=data only %}
{% endblock %}

project/open_ricostruzione/templates/pages/interventoricostruzioneprivata_list.html
{% extends 'pages/intervento_list.html' %}

{% block page_title %}Ricostruzione delle abitazioni{% endblock %}

{% block incipit %}
    <h2 class="mt-0"><span class="red">Ricostruzione</span> delle abitazioni</h2>
    <p class="lead mb-1">{% include 'includes/interventoricostruzioneprivata_text.html' %}</p>
{% endblock %}

{% block select_label %}Visualizza il livello di danno{% endblock %}

{% block more_content %}
    {% include 'includes/interventoricostruzioneprivata_charts.html' with data=data only %}
{% endblock %}